export declare type Hex = [number, number, number];
export declare const get: (grid: [number, number, number][][]) => ([q, r]: [number, number] | [number, number, number]) => [number, number, number] | null;
export declare function roundHex(hex: Hex): Hex;
export declare const hexToVector2d: (hex: [number, number, number]) => [number, number];
export declare const vector2dToHex: (vec: [number, number]) => [number, number, number];
export declare const getFromVector2d: (grid: [number, number, number][][]) => (vec: [number, number]) => [number, number, number] | null;
export declare const distanceFromTo: (hex: [number, number, number], targetHex: [number, number, number]) => number;
export declare const add: (hexA: [number, number, number]) => (hexB: [number, number, number]) => [number, number, number];
export declare const addGrid: (grid: [number, number, number][][]) => (hexA: [number, number, number]) => (hexB: [number, number, number]) => [number, number, number] | null;
export declare const subtract: (hexA: [number, number, number]) => (hexB: [number, number, number]) => [number, number, number];
export declare const subtractGrid: (grid: [number, number, number][][]) => (hexA: [number, number, number]) => (hexB: [number, number, number]) => [number, number, number] | null;
export declare const getNeighbors: (hex: [number, number, number]) => [number, number, number][];
export declare const getNeighborsGrid: (grid: [number, number, number][][]) => (hex: [number, number, number]) => [number, number, number][];
export declare const lerp: (hexA: [number, number, number], hexB: [number, number, number], dt: number) => [number, number, number];
export declare const lerpGrid: (grid: [number, number, number][][]) => (hexA: [number, number, number], hexB: [number, number, number], dt: number) => [number, number, number] | null;
export declare const lineFromTo: (src: [number, number, number], dest: [number, number, number]) => [number, number, number][];
export declare const lineFromToGrid: (grid: [number, number, number][][]) => (src: [number, number, number], dest: [number, number, number]) => [number, number, number][] | null;
export declare const getWithin: (hex: [number, number, number], radius: number) => [number, number, number][];
export declare const getWithinGrid: (grid: [number, number, number][][]) => (hex: [number, number, number], radius: number) => [number, number, number][];
export declare const getRing: (hex: [number, number, number], distance: number) => [number, number, number][];
export declare const getRingGrid: (grid: [number, number, number][][]) => (hex: [number, number, number], distance: number) => [number, number, number][];
export declare const getSpiral: (hex: [number, number, number], distance: number) => [number, number, number][];
export declare const getSpiralGrid: (grid: [number, number, number][][]) => (hex: [number, number, number], distance: number) => [number, number, number][];
export declare const getFieldOfView: (hex: [number, number, number], range: number, isBlocked: (hex: [number, number, number]) => boolean) => [number, number, number][];
export declare const getFieldOfViewGrid: (grid: [number, number, number][][]) => (hex: [number, number, number], range: number, isBlocked: (hex: [number, number, number]) => boolean) => [number, number, number][];
export declare const generateGrid: (radius: number) => [number, number, number][][];
